#!/data/data/com.termux/files/usr/bin/bash
#
source /data/data/com.termux/files/usr/local/etc/oo_namespace.sh
#
SOURCE="/data/data/com.termux/files/storage/microSD/termux/files/home/"
DEST="/data/data/com.termux/files/home/"
#
system rsync -av "$SOURCE" "$DEST"
#
