#!/data/data/com.termux/files/usr/bin/bash
#
source /data/data/com.termux/files/usr/local/etc/oo_namespace.sh
#
DEST="/data/data/com.termux/files/storage/microSD/termux/files/home/"
SOURCE="/data/data/com.termux/files/home/"
#
system rsync -rv --delete \
    --no-perms --no-owner --no-group \
    --exclude='.bash_history' \
    --exclude='.gitconfig' \
    --exclude='.lesshst' \
    --exclude='.ssh' \
    --exclude='.suroot' \
    --exclude='.termux' \
    --exclude='.viminfo' \
    "$SOURCE" "$DEST"
#
#rsync -av --delete \
#	--exclude='.bash_history' \ # --exclude='.bashrc' \
#	--exclude='.gitconfig' \
#	--exclude='.lesshst' \
#	--exclude='.ssh' \
#	--exclude='.suroot' \
#	--exclude='.termux' \
#	--exclude='.viminfo' \
#	"$SOURCE" "$DEST"
#
