#!/bin/bash
export PULSE_SERVER=127.0.0.1
#
termux-x11 :1 -xstartup "dbus-launch --sh-syntax --exit-with-session xfce4-session"
#
export DISPLAY=/data/data/com.termux/files/usr/tmp/.X11-unix/X1
#
# note: chmod +x launch-session
#
